site_name: 'Xentral Functional Documentation'
docs_dir: generated
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - content.diagram
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  -
    pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  -
    pymdownx.superfences:
      custom_fences:
        -
          name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  -
    Home: index.md
  -
    'Main Section':
      -
        'Sub Section':
          - { 'My Documentation Page': main-section/sub-section/my-documentation-page.md }
